#!/bin/bash
#SBATCH --job-name="roms"

#       %j=job_number and %N gives nodelist output="wec_real.%j.%N.out"
#SBATCH --output="roms_log.%N.out"

#       Can only use a max of 32 nodes on 'compute' partition:
#SBATCH --partition=compute
#SBATCH --nodes=2

#       Request number of cores: (Expanse has 128 cores per node)
#       If using 'compute', you will be charged 128 x number of nodes requested! Regardless of ntasks=per-node,
#       which is very important to understand to avoid being overcharged and wasting resources.
#SBATCH --ntasks-per-node=128
#SBATCH --account=cla119
#SBATCH --export=ALL

#       Max run time is 48 hours:
#SBATCH -t 12:00:00

#-----------------------------------------------------------------

# Flags needed for mvapich2:
export MV2_USE_RDMA_CM=0
export MV2_IBA_HCA=mlx5_2
export MV2 DEFAULT PORT=1

module purge
module load slurm
module load cpu/0.15.4  intel/19.1.1.217  mvapich2/2.3.4
module load netcdf-c/4.7.4
module load netcdf-fortran/4.5.3

srun --mpi=pmi2 -n 256 roms



