! This is include file "ocean3d.h".
!----- -- ------- ---- ------------
#ifdef SOLVE3D
      real u(GLOBAL_2D_ARRAY,N,3)
CSDISTRIBUTE_RESHAPE u(BLOCK_PATTERN,*,*) BLOCK_CLAUSE
      real v(GLOBAL_2D_ARRAY,N,3)
CSDISTRIBUTE_RESHAPE v(BLOCK_PATTERN,*,*) BLOCK_CLAUSE
      real t(GLOBAL_2D_ARRAY,N,3,NT)
CSDISTRIBUTE_RESHAPE t(BLOCK_PATTERN,*,*,*) BLOCK_CLAUSE
      common /ocean_u/u /ocean_v/v /ocean_t/t

      real FlxU(GLOBAL_2D_ARRAY,N)
CSDISTRIBUTE_RESHAPE  FlxU(BLOCK_PATTERN,*) BLOCK_CLAUSE
      real FlxV(GLOBAL_2D_ARRAY,N)
CSDISTRIBUTE_RESHAPE  FlxV(BLOCK_PATTERN,*) BLOCK_CLAUSE
      real We(GLOBAL_2D_ARRAY,0:N)
CSDISTRIBUTE_RESHAPE We(BLOCK_PATTERN,*) BLOCK_CLAUSE
      real Wi(GLOBAL_2D_ARRAY,0:N)
CSDISTRIBUTE_RESHAPE Wi(BLOCK_PATTERN,*) BLOCK_CLAUSE
      common /flx_FU/FlxU /flx_FV/FlxV /flx_We/We /flx_Wi/Wi
      
      real Hz(GLOBAL_2D_ARRAY,N)
CSDISTRIBUTE_RESHAPE Hz(BLOCK_PATTERN,*) BLOCK_CLAUSE
      real z_r(GLOBAL_2D_ARRAY,N)
CSDISTRIBUTE_RESHAPE z_r(BLOCK_PATTERN,*) BLOCK_CLAUSE
      real z_w(GLOBAL_2D_ARRAY,0:N)
CSDISTRIBUTE_RESHAPE z_w(BLOCK_PATTERN,*) BLOCK_CLAUSE
      common /grid_zw/z_w /grid_zr/z_r /grid_Hz/Hz

#endif  /* SOLVE3D */
