FROM mambaorg/micromamba:1.5.5

ENV ENV_NAME=roms-ci
USER root
RUN apt update && apt install -y \
    rsync make wget git cpp\
    && rm -rf /var/lib/apt/lists/*

# Write the environment.yml directly into the image                                                                                                                                                                                                                                                                                                                         
COPY environment.yml /tmp/environment.yml

# Create the environment                                                                                                                                                                                                                                                                                                                                                    
RUN micromamba create -n $ENV_NAME -f /tmp/environment.yml
ENV MAMBA_DOCKERFILE_ACTIVATE=1

# Set the default shell to run inside the environment                                                                                                                                                                                                                                                                                                                       
SHELL ["micromamba", "run", "-n", "roms-ci", "/bin/bash", "-c"]

CMD ["bash"]
ENV MPIHOME=/opt/conda/envs/roms-ci \
    NETCDFHOME=/opt/conda/envs/roms-ci \
    LD_LIBRARY_PATH=/opt/conda/envs/roms-ci/lib:$LD_LIBRARY_PATH

ENV MARBL_ROOT=/opt/MARBL
WORKDIR /opt
RUN bash -c "wget https://github.com/marbl-ecosys/MARBL/archive/refs/tags/marbl0.45.0.tar.gz \
    && tar xvf marbl0.45.0.tar.gz \
    && mv MARBL-marbl0.45.0 $MARBL_ROOT  \
    && cd $MARBL_ROOT/src \
    && make gnu USEMPI=TRUE"

COPY Containerfile /image_metadata/Containerfile
